spring:
  profiles:
    active: dev

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  # OAuth2 ??
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: Google
            client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/api/v1/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

          kakao:
            client-name: Kakao
            client-id: ${OAUTH2_KAKAO_CLIENT_ID}
            client-secret: ${OAUTH2_KAKAO_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/api/v1/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email

          naver:
            client-name: Naver
            client-id: ${OAUTH2_NAVER_CLIENT_ID}
            client-secret: ${OAUTH2_NAVER_CLIENT_SECRET:}
            redirect-uri: "{baseUrl}/api/v1/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - name
              - email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

# ?????? ??
app:
  auth:
    token-secret: ${JWT_SECRET:secret}
    access-token-expiration-msec: 3600000 # 1 hour
    refresh-token-expiration-msec: 604800000 # 7 days

      # ?? ?? ?? ??
    use-token-cookie: true  # true: ?? ??, false: ?? ???? ??
    token-cookie-name: access_token
    refresh-token-cookie-name: refresh_token

      # ??? ????? ??? ??
    allowed-redirect-origins:
      - https://example.com
      - https://app.example.com
      - http://localhost:3000  # ?? ???

    require-https: false  # ??????? true? ??
    default-redirect-url: http://localhost:3000

  cors:
    allowed-origins: "http://localhost:8080" # ?? ????? ??? ???? ??
    max-age: 3600

# ?? ??
cache:
  ttl:
    default: 300 # 5 minutes
    user: 600 # 10 minutes

# ?? ??
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    com.copago: DEBUG

# ?? ??
server:
  port: 8080
  tomcat:
    max-threads: 200
    accept-count: 100
  compression:
    enabled: true
    min-response-size: 2KB