spring:
  profiles:
    active: dev

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  security:
    oauth2:
      client:
        registration:
          google:
            client-name: Google
            client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/api/v1/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

          kakao:
            client-name: Kakao
            client-id: ${OAUTH2_KAKAO_CLIENT_ID}
            client-secret: ${OAUTH2_KAKAO_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/api/v1/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email

          naver:
            client-name: Naver
            client-id: ${OAUTH2_NAVER_CLIENT_ID}
            client-secret: ${OAUTH2_NAVER_CLIENT_SECRET:}
            redirect-uri: "{baseUrl}/api/v1/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - name
              - email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

app:
  auth:
    token-secret: ${JWT_SECRET}
    access-token-expiration: 900000 # 15 minutes
    refresh-token-expiration: 172800000 # 2 days

    use-token-cookie: true
    token-cookie-name: access_token
    refresh-token-cookie-name: refresh_token

    allowed-redirect-origins:
      - https://example.com
      - https://app.example.com
      - http://localhost:3000

    require-https: false
    default-redirect-url: http://localhost:3000

  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:https://example.com,https://app.example.com,http://localhost:3000,http://192}
    max-age: 3600

rate-limit:
  enabled: true
  default-limit: 60
  auth-limit: 10
  burst-limit: 100

cache:
  ttl:
    default: 300 # 5 minutes
    user: 600 # 10 minutes
    tokens: 3600 # 1 hour

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    com.copago: DEBUG

server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    max-threads: 200
    accept-count: 100
    remote-ip-header: X-Forwarded-For
    protocol-header: X-Forwarded-Proto
    internal-proxies: 10\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}|192\\.168\\.\\d{1,3}\\.\\d{1,3}|169\\.254\\.\\d{1,3}\\.\\d{1,3}|127\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}
  compression:
    enabled: true
    min-response-size: 2KB